### ISSUE TITLE
Caller notification/call history

### ISSUE THREAD

**Issue by boralben** [project-grand-canyon/pgc-api#2]
`/caller` GET endpoints (by id, by district, and all) should include information about the history of notifications and calls. Ex.:

```
{
        "created": "2019-07-23 15:21",
        "lastModified": "2019-07-23 15:21",
        "callerId": 524,
        "firstName": "ben",
        "lastName": "boral",
        "contactMethods": [
            "email"
        ],
        "phone": null,
        "email": "boralben+072319@gmail.com",
        "districtId": 8,
        "zipCode": "78721",
        "paused": false,
        "notifications": [
            {
                "time": "...",
                "contactMethods": ["email", "sms"],
                "districtId": 545,
                "reminderCount": 0, // 0 for first reminder that month, 1 for next follow up reminder, etc.
            }
        ]
        "calls": [
            {
                "time": "...",
                "districtId": 545
            }
        ]
    }
```

**Comment by nealprager** [comment]
Ben, are you sure you want this additional info even for queries that may return a large number of callers?  That will create a multiplicative effect (N callers, each with X notifications and Y calls).   My original notion was to only include notification/call history for the GET by ID endpoint, i.e. /callers/<caller_id>.    And even then possibly make it optional.   Do you have a specific use case in the GUI where you want history info for multiple callers?

**Comment by boralben** [comment]
You're right. It will bloat up the /callers response. The goal is to get a quick view of who has been making calls vs. who hasn't. This way admins can reach out to individuals and provide encouragement. The proposed GUI is roughly like the attached image. It provides a quick way to see the call status of each individual and to sort by that.

![call notifications](https://user-images.githubusercontent.com/1223720/64083178-966d5900-cce0-11e9-9a01-439db30bcb6f.jpg)

**Comment by nealprager** [comment]
If you're looking for a way to create a "quick view", I guess I'd lean towards just putting some counters into the base caller response, e.g. for the last year include:
     1. number of months that a notification was sent,
     2. the number of calls made,  
     3. anything else?
I could then also add a new API endpoint, e.g. "/callers/<caller_id>/history", that would return a detailed list of notifications and calls for the specified caller, including the exact time, contact methods, etc.   Would that be sufficient?

**Comment by boralben** [comment]
Thanks for proposing this idea of including a call/notification summary in the response. I originally suggested the big history blob to create a more generic, flexible API that could support other UI needs. But that would be very large. 

I think the critical piece of info for the admin quick view is the count of months of ignored notifications after each caller's most recent call (basically the most recent streak of missed calls). I'm writing count of months because we might add a follow-up reminder in the future (ex. if no call reported within 2 days, send a reminder), so it should be based on months, not notification count.

Could the /caller endpoint also include the notification day of month? The UI should show this at some point as well so that the admin can know if the person is about to get an automatic reminder.

**Comment by nealprager** [comment]
I can add the following fields to the Caller response without sacrificing much efficiency:
    reminder day of month (integer)
    date of last reminder sent to the Caller (may be null if no reminder has ever been sent)
    date of last call made by the Caller  (may be null if no call has been made)

From this you can compute the number of months by comparing the last call date to the current date.   If you need a list of all reminders sent (rather than just the most recent) I could do that but it would require an additional query to the DB.

A separate API will allow getting a full call history or notification history for a particular caller.

If this sounds OK, I should be able to commit it within a day or two.

**Comment by boralben** [comment]
I think this quick view plus the separate, more detailed call will fit the
bill perfectly. The next few days would be great. I can then get the UI
portion done over the weekend.

**Comment by nealprager** [comment]
Should be resolved now.  In addition to the new fields added to the standard Caller response, there are now two new endpoints.
GET /calls/{callerId}:   retrieves the call history for a specific caller
GET /reminders/{callerId}   retrieves reminder history (notification history) for a caller.

**Comment by boralben** [comment]
Thank you. I'll get started on the UI this weekend.
