### ISSUE TITLE
District Status

### ISSUE THREAD

**Issue by boralben** [project-grand-canyon/pgc-api#28]
The admins for some districts want to pause calls. Their congressional offices are closed, or staffed by a skeleton crew and not receptive to calls about climate change during this emergency.

As first step to pausing calls in a district, we should track the status of each district

Acceptance Criteria

Adds nonull status column to district
possible values: active and covid_paused
default to active
all requests and responses to /districts API endpoints appropriately process the `status` attribute

**Comment by vnagel** [comment]
should we separate pausing the district from the reason for pausing the district? e.g. have a `paused` column and a `paused_reason` column. This would support allowing admins to pause a district in the future, e.g. for reasons specific to a district, without us having to make changes to the code.

**Comment by boralben** [comment]
I had a similar thought but decided to do this because there's so much
additional work associated with pausing (like updating the thank you for
signing up page, sending a note with an explanation, updating the call in
page etc.) that I think it should be more of a manual thing every time.

**Comment by vnagel** [comment]
What about using the 2 column approach, but only allowing the covid case for now? Just so we won't have to refactor as much if we ever decide to support it in the future.

**Comment by vnagel** [comment]
done
