### ISSUE TITLE
ReminderService doesn't send notifications if district status is `covid_paused`

### ISSUE THREAD

**Issue by boralben** [project-grand-canyon/pgc-api#33]
`ReminderService` only sends a notification if the caller is in a district marked `active`.
*Acceptance Criteria*
* If I am in a district marked `active`, I get a notification on my call-in day
* If I am in a district marked `covid_paused`, I don't get a notification on my call-in day

**Comment by boralben** [comment]
Blocked by https://github.com/project-grand-canyon/pgc-api/issues/28

**Comment by vnagel** [comment]
> ReminderService only sends a notification if the caller is in a district marked active.
Acceptance Criteria

Should this be the target district or the caller's district?

**Comment by boralben** [comment]
Great question. We're going to start off by considering the caller's district, not their target district.
