### ISSUE TITLE
Weekly Admin Reminder

### ISSUE THREAD

**Issue by boralben** [project-grand-canyon/pgc-api#34]
Every Sunday evening, send an email to the admins whose districts have `status == covid_paused`.

*Acceptance Criteria*
* Job kicks off on Sunday evening at 8PM Eastern
* If an admin oversees a district whose status is `covid_paused`, they will get one email (even if they oversee >1 districts with that status)
* If the statuses of all of the districts an admin oversees are all `active`, they will not get an email
* Email contents:
```
Hello,

You are receiving this email from the Monthly Calling Campaign as a reminder that districts CA-3, CA-4, and CA-Junior Senator ---for example---, have their status "paused for COVID-19."

If that is still appropriate, then no action is needed from you. If the situation has improved enough to start calling about climate change, please re-enable your district by logging into the admin portal at admin.cclcalls.org, and navigating to the "Representatives" tab. If there are multiple admins for a district you oversee, don't forget to coordinate with them when making this decision. You can see a list of admins by district by navigating to the "Admins" tab.

Thank you,
The MCC team
```

**Comment by vnagel** [comment]
Does the "Junior Senator" part come from the District `info` field?

**Comment by boralben** [comment]
Ah, good Q. district_number -1 is Senior Senator and -2 is Junior Senator. I think this logic is not centralized to one location in the codebase, so it could probably be put in the `District` object as a `officialTitle()` function where it would return "Representative," "Junior Senator," or "Senior Senator."
